create table if not exists usuarios (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    email varchar(160) not null unique,
    telefone varchar(20),
    data_nascimento date,
    senha varchar(255) not null,
    created_at timestamp with time zone not null default now()
);

create table if not exists livros (
    id bigint generated by default as identity primary key,
    nome_autor varchar(160) not null,
    titulo_livro varchar(200) not null,
    editora varchar(120),
    quantidade integer not null default 0,
    ano_publicacao integer,
    genero varchar(100),
    created_at timestamp with time zone not null default now(),

    constraint livros_quantidade_nao_negativa check (quantidade >= 0),
    constraint livros_ano_publicacao_valido check (
        ano_publicacao is null or ano_publicacao >= 0
    )
);

create table if not exists emprestimos (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null,
    livro_id bigint not null,
    data_emprestimo date not null default current_date,
    data_devolucao date,
    status varchar(20) not null default 'emprestado',
    created_at timestamp with time zone not null default now(),

    constraint emprestimos_usuario_fk foreign key (usuario_id)
        references usuarios (id),
    constraint emprestimos_livro_fk foreign key (livro_id)
        references livros (id),
    constraint emprestimos_status_valido check (status in ('emprestado', 'devolvido')),
    constraint emprestimos_data_devolucao_valida check (
        data_devolucao is null or data_devolucao >= data_emprestimo
    )
);
